---
language: generic

sudo: false

git:
  depth: 2

jobs:
  include:
    - stage: build
      name: Container Build

      # only want to run when code is merged to master branch
      if: type != pull_request AND branch = master

      # run preflight script which will exit Travis if Dockerfile is unchanged
      before_script:
        - ./preflight.sh || travis_terminate 0

      # if stage passes preflight push new container to quay
      script:
        - ./deploy-on-quay.sh

stages:
  - build
