---
language: generic

stages:
  - name: build

    # only want to run when code is merged to master branch
    if: branch = master

    # stage config
    sudo: false
    git:
      depth: 2

    # clone CI repo and run preflight script which will exit Travis if Dockerfile is unchanged
    before_script:
      - git clone --depth=2 https://github.com/openstack-k8s-operators/openstack-k8s-operators-ci.git
      - ./openstack-k8s-operators-ci/preflight.sh

    # if stage passes prelight push new container to quay
    script:
      - ./openstack-k8s-operators-ci/deploy-on-quay.sh
